name: ecedi - Update Rennes theme submodule

on:
  workflow_call:
    secrets:
      ECEDI_PAT_TOKEN:
        required: true

jobs:
  update-rennes-theme:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération des données
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ECEDI_PAT_TOKEN }}
          submodules: true

      - name: Mise à jour des submodules ecedi
        run: |
          git submodule update --remote themes/rennes-hugo-theme
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🚀 Updated Rennes theme version" || echo "No changes to commit"
          git push origin main