name: ecedi - Update theme submodule

on:
  workflow_call:
    inputs:
      submodule_path:
        required: true
        type: string
    secrets:
      ECEDI_PAT_TOKEN:
        required: true

jobs:
  update-theme:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération des données
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ECEDI_PAT_TOKEN }}
          submodules: true

      - name: Mise à jour du submodule
        run: |
          git submodule update --remote ${{ inputs.submodule_path }}
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ${{ inputs.submodule_path }}
          git commit -m "Updated submodule: ${{ inputs.submodule_path }}" || echo "No changes to commit"
          git push origin main
