name: ecedi - Update Search Engine Indexer Submodule

on:
  workflow_call:
    secrets:
      ECEDI_PAT_TOKEN:
        required: true

jobs:
  update-search-engine-indexer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout avec sous-modules
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ECEDI_PAT_TOKEN }}
          submodules: true

      - name: 🔍 Check if submodule exists (and add it if missing)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          mkdir -p modules
          
          if git config --file .gitmodules --get-regexp path | grep -q "modules/search-engine-indexer"; then
            echo "✅ Submodule already declared in .gitmodules."
          else
            echo "🔧 Submodule 'search-engine-indexer' is missing. Adding it..."
            git submodule add https://github.com/osunyorg/rennes-search-engine-indexer.git modules/search-engine-indexer
            git add .gitmodules modules/search-engine-indexer
            git commit -m "Added 'search-engine-indexer' submodule"
          fi

      - name: 🧩 Mise à jour du submodule indexer
        run: |
          git submodule update --remote modules/search-engine-indexer
          git add modules/search-engine-indexer
          git commit -m "🚀 Updated Search engine indexer version" || echo "No changes to commit"
          git push origin main
